# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import anomalydetection_pb2 as anomalydetection__pb2


class ModelServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inference = channel.unary_unary(
                '/anomalydetectionmodel.ModelService/Inference',
                request_serializer=anomalydetection__pb2.InferenceReq.SerializeToString,
                response_deserializer=anomalydetection__pb2.InferenceRes.FromString,
                )


class ModelServiceServicer(object):
    """The service definition.
    """

    def Inference(self, request, context):
        """Sends Data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inference': grpc.unary_unary_rpc_method_handler(
                    servicer.Inference,
                    request_deserializer=anomalydetection__pb2.InferenceReq.FromString,
                    response_serializer=anomalydetection__pb2.InferenceRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'anomalydetectionmodel.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """The service definition.
    """

    @staticmethod
    def Inference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/anomalydetectionmodel.ModelService/Inference',
            anomalydetection__pb2.InferenceReq.SerializeToString,
            anomalydetection__pb2.InferenceRes.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
