# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomalydetection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anomalydetection.proto',
  package='anomalydetectionmodel',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x61nomalydetection.proto\x12\x15\x61nomalydetectionmodel\"4\n\x0bTypeMachine\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08pressure\x18\x02 \x01(\x02\"4\n\x0bTypeAmbient\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\"\x89\x01\n\x0cInferenceReq\x12\x33\n\x07machine\x18\x01 \x01(\x0b\x32\".anomalydetectionmodel.TypeMachine\x12\x33\n\x07\x61mbient\x18\x02 \x01(\x0b\x32\".anomalydetectionmodel.TypeAmbient\x12\x0f\n\x07\x61nomaly\x18\x03 \x01(\x08\"\x89\x01\n\x0cInferenceRes\x12\x33\n\x07machine\x18\x01 \x01(\x0b\x32\".anomalydetectionmodel.TypeMachine\x12\x33\n\x07\x61mbient\x18\x02 \x01(\x0b\x32\".anomalydetectionmodel.TypeAmbient\x12\x0f\n\x07\x61nomaly\x18\x03 \x01(\x08\x32g\n\x0cModelService\x12W\n\tInference\x12#.anomalydetectionmodel.InferenceReq\x1a#.anomalydetectionmodel.InferenceRes\"\x00\x62\x06proto3'
)




_TYPEMACHINE = _descriptor.Descriptor(
  name='TypeMachine',
  full_name='anomalydetectionmodel.TypeMachine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='anomalydetectionmodel.TypeMachine.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='anomalydetectionmodel.TypeMachine.pressure', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=101,
)


_TYPEAMBIENT = _descriptor.Descriptor(
  name='TypeAmbient',
  full_name='anomalydetectionmodel.TypeAmbient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='anomalydetectionmodel.TypeAmbient.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='anomalydetectionmodel.TypeAmbient.humidity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=155,
)


_INFERENCEREQ = _descriptor.Descriptor(
  name='InferenceReq',
  full_name='anomalydetectionmodel.InferenceReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine', full_name='anomalydetectionmodel.InferenceReq.machine', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ambient', full_name='anomalydetectionmodel.InferenceReq.ambient', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anomaly', full_name='anomalydetectionmodel.InferenceReq.anomaly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=295,
)


_INFERENCERES = _descriptor.Descriptor(
  name='InferenceRes',
  full_name='anomalydetectionmodel.InferenceRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine', full_name='anomalydetectionmodel.InferenceRes.machine', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ambient', full_name='anomalydetectionmodel.InferenceRes.ambient', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='anomaly', full_name='anomalydetectionmodel.InferenceRes.anomaly', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=435,
)

_INFERENCEREQ.fields_by_name['machine'].message_type = _TYPEMACHINE
_INFERENCEREQ.fields_by_name['ambient'].message_type = _TYPEAMBIENT
_INFERENCERES.fields_by_name['machine'].message_type = _TYPEMACHINE
_INFERENCERES.fields_by_name['ambient'].message_type = _TYPEAMBIENT
DESCRIPTOR.message_types_by_name['TypeMachine'] = _TYPEMACHINE
DESCRIPTOR.message_types_by_name['TypeAmbient'] = _TYPEAMBIENT
DESCRIPTOR.message_types_by_name['InferenceReq'] = _INFERENCEREQ
DESCRIPTOR.message_types_by_name['InferenceRes'] = _INFERENCERES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TypeMachine = _reflection.GeneratedProtocolMessageType('TypeMachine', (_message.Message,), {
  'DESCRIPTOR' : _TYPEMACHINE,
  '__module__' : 'anomalydetection_pb2'
  # @@protoc_insertion_point(class_scope:anomalydetectionmodel.TypeMachine)
  })
_sym_db.RegisterMessage(TypeMachine)

TypeAmbient = _reflection.GeneratedProtocolMessageType('TypeAmbient', (_message.Message,), {
  'DESCRIPTOR' : _TYPEAMBIENT,
  '__module__' : 'anomalydetection_pb2'
  # @@protoc_insertion_point(class_scope:anomalydetectionmodel.TypeAmbient)
  })
_sym_db.RegisterMessage(TypeAmbient)

InferenceReq = _reflection.GeneratedProtocolMessageType('InferenceReq', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEREQ,
  '__module__' : 'anomalydetection_pb2'
  # @@protoc_insertion_point(class_scope:anomalydetectionmodel.InferenceReq)
  })
_sym_db.RegisterMessage(InferenceReq)

InferenceRes = _reflection.GeneratedProtocolMessageType('InferenceRes', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCERES,
  '__module__' : 'anomalydetection_pb2'
  # @@protoc_insertion_point(class_scope:anomalydetectionmodel.InferenceRes)
  })
_sym_db.RegisterMessage(InferenceRes)



_MODELSERVICE = _descriptor.ServiceDescriptor(
  name='ModelService',
  full_name='anomalydetectionmodel.ModelService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=437,
  serialized_end=540,
  methods=[
  _descriptor.MethodDescriptor(
    name='Inference',
    full_name='anomalydetectionmodel.ModelService.Inference',
    index=0,
    containing_service=None,
    input_type=_INFERENCEREQ,
    output_type=_INFERENCERES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODELSERVICE)

DESCRIPTOR.services_by_name['ModelService'] = _MODELSERVICE

# @@protoc_insertion_point(module_scope)
